/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedActivityRouteImport } from './routes/_authenticated/activity'
import { Route as AuthenticatedAgenciesRouteImport } from './routes/_authenticated/agencies'
import { Route as AuthenticatedCleaningRouteImport } from './routes/_authenticated/cleaning'
import { Route as AuthenticatedCleaningHistoryRouteImport } from './routes/_authenticated/cleaning-history'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedHistoryRouteImport } from './routes/_authenticated/history'
import { Route as AuthenticatedInboxRouteImport } from './routes/_authenticated/inbox'
import { Route as AuthenticatedJobsRouteImport } from './routes/_authenticated/jobs'
import { Route as AuthenticatedPeopleRouteImport } from './routes/_authenticated/people'
import { Route as AuthenticatedPerformanceRouteImport } from './routes/_authenticated/performance'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedRequestsRouteImport } from './routes/_authenticated/requests'
import { Route as AuthenticatedReviewsRouteImport } from './routes/_authenticated/reviews'
import { Route as AuthenticatedReviewsArchiveRouteImport } from './routes/_authenticated/reviews-archive'
import { Route as AuthenticatedRosterRouteImport } from './routes/_authenticated/roster'
import { Route as AuthenticatedShopRouteImport } from './routes/_authenticated/shop'
import { Route as AuthenticatedTasksRouteImport } from './routes/_authenticated/tasks'
import { Route as GCodeRouteImport } from './routes/g.$code'
import { Route as AuthenticatedOnboardingRoleRouteImport } from './routes/_authenticated/onboarding/role'
import { Route as AuthenticatedPropertiesIndexRouteImport } from './routes/_authenticated/properties.index'
import { Route as AuthenticatedPropertiesPropertyIdRouteImport } from './routes/_authenticated/properties.$propertyId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedActivityRoute = AuthenticatedActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAgenciesRoute = AuthenticatedAgenciesRouteImport.update({
  id: '/agencies',
  path: '/agencies',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCleaningRoute = AuthenticatedCleaningRouteImport.update({
  id: '/cleaning',
  path: '/cleaning',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCleaningHistoryRoute =
  AuthenticatedCleaningHistoryRouteImport.update({
    id: '/cleaning-history',
    path: '/cleaning-history',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHistoryRoute = AuthenticatedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInboxRoute = AuthenticatedInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedJobsRoute = AuthenticatedJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPeopleRoute = AuthenticatedPeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPerformanceRoute =
  AuthenticatedPerformanceRouteImport.update({
    id: '/performance',
    path: '/performance',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRequestsRoute = AuthenticatedRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReviewsRoute = AuthenticatedReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReviewsArchiveRoute =
  AuthenticatedReviewsArchiveRouteImport.update({
    id: '/reviews-archive',
    path: '/reviews-archive',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRosterRoute = AuthenticatedRosterRouteImport.update({
  id: '/roster',
  path: '/roster',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedShopRoute = AuthenticatedShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTasksRoute = AuthenticatedTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const GCodeRoute = GCodeRouteImport.update({
  id: '/g/$code',
  path: '/g/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOnboardingRoleRoute =
  AuthenticatedOnboardingRoleRouteImport.update({
    id: '/onboarding/role',
    path: '/onboarding/role',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPropertiesIndexRoute =
  AuthenticatedPropertiesIndexRouteImport.update({
    id: '/properties/',
    path: '/properties/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPropertiesPropertyIdRoute =
  AuthenticatedPropertiesPropertyIdRouteImport.update({
    id: '/properties/$propertyId',
    path: '/properties/$propertyId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/activity': typeof AuthenticatedActivityRoute
  '/agencies': typeof AuthenticatedAgenciesRoute
  '/cleaning': typeof AuthenticatedCleaningRoute
  '/cleaning-history': typeof AuthenticatedCleaningHistoryRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/inbox': typeof AuthenticatedInboxRoute
  '/jobs': typeof AuthenticatedJobsRoute
  '/people': typeof AuthenticatedPeopleRoute
  '/performance': typeof AuthenticatedPerformanceRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/requests': typeof AuthenticatedRequestsRoute
  '/reviews': typeof AuthenticatedReviewsRoute
  '/reviews-archive': typeof AuthenticatedReviewsArchiveRoute
  '/roster': typeof AuthenticatedRosterRoute
  '/shop': typeof AuthenticatedShopRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/g/$code': typeof GCodeRoute
  '/onboarding/role': typeof AuthenticatedOnboardingRoleRoute
  '/properties/$propertyId': typeof AuthenticatedPropertiesPropertyIdRoute
  '/properties/': typeof AuthenticatedPropertiesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/activity': typeof AuthenticatedActivityRoute
  '/agencies': typeof AuthenticatedAgenciesRoute
  '/cleaning': typeof AuthenticatedCleaningRoute
  '/cleaning-history': typeof AuthenticatedCleaningHistoryRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/inbox': typeof AuthenticatedInboxRoute
  '/jobs': typeof AuthenticatedJobsRoute
  '/people': typeof AuthenticatedPeopleRoute
  '/performance': typeof AuthenticatedPerformanceRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/requests': typeof AuthenticatedRequestsRoute
  '/reviews': typeof AuthenticatedReviewsRoute
  '/reviews-archive': typeof AuthenticatedReviewsArchiveRoute
  '/roster': typeof AuthenticatedRosterRoute
  '/shop': typeof AuthenticatedShopRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/g/$code': typeof GCodeRoute
  '/onboarding/role': typeof AuthenticatedOnboardingRoleRoute
  '/properties/$propertyId': typeof AuthenticatedPropertiesPropertyIdRoute
  '/properties': typeof AuthenticatedPropertiesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/activity': typeof AuthenticatedActivityRoute
  '/_authenticated/agencies': typeof AuthenticatedAgenciesRoute
  '/_authenticated/cleaning': typeof AuthenticatedCleaningRoute
  '/_authenticated/cleaning-history': typeof AuthenticatedCleaningHistoryRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/history': typeof AuthenticatedHistoryRoute
  '/_authenticated/inbox': typeof AuthenticatedInboxRoute
  '/_authenticated/jobs': typeof AuthenticatedJobsRoute
  '/_authenticated/people': typeof AuthenticatedPeopleRoute
  '/_authenticated/performance': typeof AuthenticatedPerformanceRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/requests': typeof AuthenticatedRequestsRoute
  '/_authenticated/reviews': typeof AuthenticatedReviewsRoute
  '/_authenticated/reviews-archive': typeof AuthenticatedReviewsArchiveRoute
  '/_authenticated/roster': typeof AuthenticatedRosterRoute
  '/_authenticated/shop': typeof AuthenticatedShopRoute
  '/_authenticated/tasks': typeof AuthenticatedTasksRoute
  '/g/$code': typeof GCodeRoute
  '/_authenticated/onboarding/role': typeof AuthenticatedOnboardingRoleRoute
  '/_authenticated/properties/$propertyId': typeof AuthenticatedPropertiesPropertyIdRoute
  '/_authenticated/properties/': typeof AuthenticatedPropertiesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/activity'
    | '/agencies'
    | '/cleaning'
    | '/cleaning-history'
    | '/dashboard'
    | '/history'
    | '/inbox'
    | '/jobs'
    | '/people'
    | '/performance'
    | '/profile'
    | '/requests'
    | '/reviews'
    | '/reviews-archive'
    | '/roster'
    | '/shop'
    | '/tasks'
    | '/g/$code'
    | '/onboarding/role'
    | '/properties/$propertyId'
    | '/properties/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/activity'
    | '/agencies'
    | '/cleaning'
    | '/cleaning-history'
    | '/dashboard'
    | '/history'
    | '/inbox'
    | '/jobs'
    | '/people'
    | '/performance'
    | '/profile'
    | '/requests'
    | '/reviews'
    | '/reviews-archive'
    | '/roster'
    | '/shop'
    | '/tasks'
    | '/g/$code'
    | '/onboarding/role'
    | '/properties/$propertyId'
    | '/properties'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/activity'
    | '/_authenticated/agencies'
    | '/_authenticated/cleaning'
    | '/_authenticated/cleaning-history'
    | '/_authenticated/dashboard'
    | '/_authenticated/history'
    | '/_authenticated/inbox'
    | '/_authenticated/jobs'
    | '/_authenticated/people'
    | '/_authenticated/performance'
    | '/_authenticated/profile'
    | '/_authenticated/requests'
    | '/_authenticated/reviews'
    | '/_authenticated/reviews-archive'
    | '/_authenticated/roster'
    | '/_authenticated/shop'
    | '/_authenticated/tasks'
    | '/g/$code'
    | '/_authenticated/onboarding/role'
    | '/_authenticated/properties/$propertyId'
    | '/_authenticated/properties/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  GCodeRoute: typeof GCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/activity': {
      id: '/_authenticated/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof AuthenticatedActivityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agencies': {
      id: '/_authenticated/agencies'
      path: '/agencies'
      fullPath: '/agencies'
      preLoaderRoute: typeof AuthenticatedAgenciesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cleaning': {
      id: '/_authenticated/cleaning'
      path: '/cleaning'
      fullPath: '/cleaning'
      preLoaderRoute: typeof AuthenticatedCleaningRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cleaning-history': {
      id: '/_authenticated/cleaning-history'
      path: '/cleaning-history'
      fullPath: '/cleaning-history'
      preLoaderRoute: typeof AuthenticatedCleaningHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/history': {
      id: '/_authenticated/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthenticatedHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inbox': {
      id: '/_authenticated/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof AuthenticatedInboxRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/jobs': {
      id: '/_authenticated/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof AuthenticatedJobsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/people': {
      id: '/_authenticated/people'
      path: '/people'
      fullPath: '/people'
      preLoaderRoute: typeof AuthenticatedPeopleRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/performance': {
      id: '/_authenticated/performance'
      path: '/performance'
      fullPath: '/performance'
      preLoaderRoute: typeof AuthenticatedPerformanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/requests': {
      id: '/_authenticated/requests'
      path: '/requests'
      fullPath: '/requests'
      preLoaderRoute: typeof AuthenticatedRequestsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reviews': {
      id: '/_authenticated/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof AuthenticatedReviewsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reviews-archive': {
      id: '/_authenticated/reviews-archive'
      path: '/reviews-archive'
      fullPath: '/reviews-archive'
      preLoaderRoute: typeof AuthenticatedReviewsArchiveRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/roster': {
      id: '/_authenticated/roster'
      path: '/roster'
      fullPath: '/roster'
      preLoaderRoute: typeof AuthenticatedRosterRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/shop': {
      id: '/_authenticated/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof AuthenticatedShopRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tasks': {
      id: '/_authenticated/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/g/$code': {
      id: '/g/$code'
      path: '/g/$code'
      fullPath: '/g/$code'
      preLoaderRoute: typeof GCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/onboarding/role': {
      id: '/_authenticated/onboarding/role'
      path: '/onboarding/role'
      fullPath: '/onboarding/role'
      preLoaderRoute: typeof AuthenticatedOnboardingRoleRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/properties/': {
      id: '/_authenticated/properties/'
      path: '/properties'
      fullPath: '/properties/'
      preLoaderRoute: typeof AuthenticatedPropertiesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/properties/$propertyId': {
      id: '/_authenticated/properties/$propertyId'
      path: '/properties/$propertyId'
      fullPath: '/properties/$propertyId'
      preLoaderRoute: typeof AuthenticatedPropertiesPropertyIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedActivityRoute: typeof AuthenticatedActivityRoute
  AuthenticatedAgenciesRoute: typeof AuthenticatedAgenciesRoute
  AuthenticatedCleaningRoute: typeof AuthenticatedCleaningRoute
  AuthenticatedCleaningHistoryRoute: typeof AuthenticatedCleaningHistoryRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedHistoryRoute: typeof AuthenticatedHistoryRoute
  AuthenticatedInboxRoute: typeof AuthenticatedInboxRoute
  AuthenticatedJobsRoute: typeof AuthenticatedJobsRoute
  AuthenticatedPeopleRoute: typeof AuthenticatedPeopleRoute
  AuthenticatedPerformanceRoute: typeof AuthenticatedPerformanceRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedRequestsRoute: typeof AuthenticatedRequestsRoute
  AuthenticatedReviewsRoute: typeof AuthenticatedReviewsRoute
  AuthenticatedReviewsArchiveRoute: typeof AuthenticatedReviewsArchiveRoute
  AuthenticatedRosterRoute: typeof AuthenticatedRosterRoute
  AuthenticatedShopRoute: typeof AuthenticatedShopRoute
  AuthenticatedTasksRoute: typeof AuthenticatedTasksRoute
  AuthenticatedOnboardingRoleRoute: typeof AuthenticatedOnboardingRoleRoute
  AuthenticatedPropertiesPropertyIdRoute: typeof AuthenticatedPropertiesPropertyIdRoute
  AuthenticatedPropertiesIndexRoute: typeof AuthenticatedPropertiesIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedActivityRoute: AuthenticatedActivityRoute,
  AuthenticatedAgenciesRoute: AuthenticatedAgenciesRoute,
  AuthenticatedCleaningRoute: AuthenticatedCleaningRoute,
  AuthenticatedCleaningHistoryRoute: AuthenticatedCleaningHistoryRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedHistoryRoute: AuthenticatedHistoryRoute,
  AuthenticatedInboxRoute: AuthenticatedInboxRoute,
  AuthenticatedJobsRoute: AuthenticatedJobsRoute,
  AuthenticatedPeopleRoute: AuthenticatedPeopleRoute,
  AuthenticatedPerformanceRoute: AuthenticatedPerformanceRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedRequestsRoute: AuthenticatedRequestsRoute,
  AuthenticatedReviewsRoute: AuthenticatedReviewsRoute,
  AuthenticatedReviewsArchiveRoute: AuthenticatedReviewsArchiveRoute,
  AuthenticatedRosterRoute: AuthenticatedRosterRoute,
  AuthenticatedShopRoute: AuthenticatedShopRoute,
  AuthenticatedTasksRoute: AuthenticatedTasksRoute,
  AuthenticatedOnboardingRoleRoute: AuthenticatedOnboardingRoleRoute,
  AuthenticatedPropertiesPropertyIdRoute:
    AuthenticatedPropertiesPropertyIdRoute,
  AuthenticatedPropertiesIndexRoute: AuthenticatedPropertiesIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  GCodeRoute: GCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
